syntax = "proto3";
package crystallization;

import "google/protobuf/timestamp.proto";
import "crystallization-prediction.proto";

service CrystallizationService {
  rpc CreateDailyMeasurement(CreateDailyMeasurementRequest) returns (CreateDailyMeasurementResponse);
  rpc GetDailyMeasurementByDate(GetDailyMeasurementByDateRequest) returns (GetDailyMeasurementByDateResponse);
  rpc GetDailyMeasurementsByDateRange(GetDailyMeasurementsByDateRangeRequest) returns (GetDailyMeasurementsByDateRangeResponse);
  rpc UpdateDailyMeasurementById(UpdateDailyMeasurementByIdRequest) returns (UpdateDailyMeasurementByIdResponse);
  rpc DeleteDailyMeasurementById(DeleteDailyMeasurementByIdRequest) returns (DeleteDailyMeasurementByIdResponse);
  rpc GetPredictions(predictions.PredictionRequest) returns (predictions.PredictionResponse);
  rpc GetPredictedDailyMeasurement(GetPredictedDailyMeasurementRequest) returns (GetPredictedDailyMeasurementResponse);
  rpc GetPredictedMonthlyProduction(GetPredictedMonthlyProductionRequest) returns (GetPredictedMonthlyProductionResponse);
}

message CreateDailyMeasurementRequest {
  string date = 1;
  double waterTemperature = 2;
  double lagoon = 3;
  double orBrineLevel = 4;
  double orBoundLevel = 5;
  double irBrineLevel = 6;
  double irBoundLevel = 7;
  double eastChannel = 8;
  double westChannel = 9;
}

message CreateDailyMeasurementResponse {
  bool success = 1;
  string message = 2;
  DailyMeasurement data = 3;
}

message Parameters {
  double water_temperature = 1;
  double lagoon = 2;
  double OR_brine_level = 3;
  double OR_bund_level = 4;
  double IR_brine_level = 5;
  double IR_bound_level = 6;
  double East_channel = 7;
  double West_channel = 8;
}

message Weather {
  double temperature_mean = 1;
  double temperature_max = 2;
  double temperature_min = 3;
  double rain_sum = 4;
  double wind_speed_max = 5;
  double wind_gusts_max = 6;
  double relative_humidity_mean = 7;
}

message DailyMeasurement {
  string date = 1;
  int32 dayNumber = 2;
  Parameters parameters = 3;
  Weather weather = 4;
  string _id = 5;
  string createdAt = 6;
  string updatedAt = 7;
}

message GetDailyMeasurementByDateRequest {
  string date = 1;
}

message GetDailyMeasurementByDateResponse {
  bool success = 1;
  string message = 2;
  DailyMeasurement data = 3;
}

message GetDailyMeasurementsByDateRangeRequest {
  string startDate = 1;
  string endDate = 2;
}

message GetDailyMeasurementsByDateRangeResponse {
  bool success = 1;
  string message = 2;
  repeated DailyMeasurement data = 3;
}

message UpdateDailyMeasurementByIdRequest {
  string id = 1;
  double waterTemperature = 2;
  double lagoon = 3;
  double orBrineLevel = 4;
  double orBoundLevel = 5;
  double irBrineLevel = 6;
  double irBoundLevel = 7;
  double eastChannel = 8;
  double westChannel = 9;
}

message UpdateDailyMeasurementByIdResponse {
  bool success = 1;
  string message = 2;
  DailyMeasurement data = 3;
}

message DeleteDailyMeasurementByIdRequest {
  string id = 1;
}

message DeleteDailyMeasurementByIdResponse {
  bool success = 1;
  string message = 2;
}

message GetPredictedDailyMeasurementRequest {
  string startDate = 1;
  string endDate = 2;
}

message PredictedDailyMeasurement {
  string _id = 1;
  string date = 2;
  int32 dayNumber = 3;
  PredictedParameters parameters = 4;
  PredictedWeather weather = 5;
  string createdAt = 6;
  string updatedAt = 7;
}

message PredictedParameters {
  double water_temperature = 1;
  double lagoon = 2;
  double OR_brine_level = 3;
  double OR_bund_level = 4;
  double IR_brine_level = 5;
  double IR_bound_level = 6;
  double East_channel = 7;
  double West_channel = 8;
}

message PredictedWeather {
  double temperature_mean = 1;
  double temperature_min = 2;
  double temperature_max = 3;
  double rain_sum = 4;
  double wind_speed_max = 5;
  double wind_gusts_max = 6;
  double relative_humidity_mean = 7;
}

message GetPredictedDailyMeasurementResponse {
  bool success = 1;
  string message = 2;
  repeated PredictedDailyMeasurement data = 3;
}

message GetPredictedMonthlyProductionRequest {
  string startMonth = 1;
  string endMonth = 2;
}

message PredictedMonthlyProduction {
  string _id = 1;
  string month = 2;
  int32 monthNumber = 3;
  double productionForecast = 4;
  double lowerBound = 5;
  double upperBound = 6;
  string season = 7;
  string createdAt = 8;
  string updatedAt = 9;
}

message GetPredictedMonthlyProductionResponse {
  bool success = 1;
  string message = 2;
  repeated PredictedMonthlyProduction data = 3;
}

