syntax = "proto3";
package saltproduction;

service SaltProductionService {
  rpc CreateActualMonthlyProduction(CreateActualMonthlyProductionRequest) returns (CreateActualMonthlyProductionResponse);
  rpc GetActualMonthlyProductionByRange(GetActualMonthlyProductionByRangeRequest) returns (GetActualMonthlyProductionByRangeResponse);
  rpc GetActualMonthlyProductionById(GetActualMonthlyProductionByIdRequest) returns (GetActualMonthlyProductionByIdResponse);
  rpc GetActualMonthlyProductionByMonth(GetActualMonthlyProductionByMonthRequest) returns (GetActualMonthlyProductionByMonthResponse);
  rpc UpdateActualMonthlyProduction(UpdateActualMonthlyProductionRequest) returns (UpdateActualMonthlyProductionResponse);
  rpc DeleteActualMonthlyProduction(DeleteActualMonthlyProductionRequest) returns (DeleteActualMonthlyProductionResponse);
}

// Messages
message ActualMonthlyProduction {
  string _id = 1;
  string month = 2;
  double production_volume = 3;
  string season = 4;
  string createdAt = 5;
  string updatedAt = 6;
}

// Create
message CreateActualMonthlyProductionRequest {
  string month = 1;
  double production_volume = 2;
  string season = 3;
}

message CreateActualMonthlyProductionResponse {
  bool success = 1;
  string message = 2;
  ActualMonthlyProduction data = 3;
}

// Get by Range
message GetActualMonthlyProductionByRangeRequest {
  string startMonth = 1;
  string endMonth = 2;
}

message GetActualMonthlyProductionByRangeResponse {
  bool success = 1;
  string message = 2;
  repeated ActualMonthlyProduction data = 3;
}

// Get by ID
message GetActualMonthlyProductionByIdRequest {
  string id = 1;
}

message GetActualMonthlyProductionByIdResponse {
  bool success = 1;
  string message = 2;
  ActualMonthlyProduction data = 3;
}

// Get by Month
message GetActualMonthlyProductionByMonthRequest {
  string month = 1;
}

message GetActualMonthlyProductionByMonthResponse {
  bool success = 1;
  string message = 2;
  ActualMonthlyProduction data = 3;
}

// Update
message UpdateActualMonthlyProductionRequest {
  string id = 1;
  double production_volume = 2;
  string season = 3;
}

message UpdateActualMonthlyProductionResponse {
  bool success = 1;
  string message = 2;
  ActualMonthlyProduction data = 3;
}

// Delete
message DeleteActualMonthlyProductionRequest {
  string id = 1;
}

message DeleteActualMonthlyProductionResponse {
  bool success = 1;
  string message = 2;
}
